#spring.datasource.url=
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.jpa.hibernate.ddl-auto=validate
  #un commentaire
#spring.flyway.baselineOnMigrate = false
#  valueTest=value


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/players_management
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
  flyway:
    baseline-on-migrate: false

#si on veut l'appler avec spring.valueTest la variable doit pas etre du meme niveau que spring
valueTest: value
file.input: liste_coffe.csv